### ISSUE TITLE
support empty lines at start of file

### ISSUE THREAD

**Issue by theflow** [opencolor-tools/js-oco-parser#9]
this should parse:

```


Produktgruppen:
  oct/view: square
  Privat: #FF8300
  Unternehmen: #009DE1
  Entwickler: #BF047E
```

getting a `Error: Parse error on line 1: Unexpected 'NEWLINE'`

**Comment by theflow** [comment]
ehm:

```

Produktgruppen:
  oct/view: square
  Privat: #FF8300
  Unternehmen: #009DE1
  Entwickler: #BF047E
```
